on:
  push:
    branches:
      - main
    paths-ignore:
      - 'CHANGELOG.md'

jobs:
  build-gem:
    name: Build gem
    runs-on: ubuntu-18.04
    steps:
      - name: Code Checkout
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3.3.0
      - name: Set Ruby
        uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: '2.6'
      - name: Build RubyGem
        run: gem build my-vagrant-guest-plugin-ruby-template.gemspec
        working-directory: ${{github.workspace}}
